// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjx-QqGTi-OfuPSH7RNM_QjwKHo7XIFoM',
    appId: '1:853950761426:web:37b44d3eb52a3365abe00b',
    messagingSenderId: '853950761426',
    projectId: 'note-with-firebase-33215',
    authDomain: 'note-with-firebase-33215.firebaseapp.com',
    storageBucket: 'note-with-firebase-33215.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxSre7q5pXO7HRFtLtCjMvk6uPwJPl-i8',
    appId: '1:853950761426:android:362c6a478d91b6f6abe00b',
    messagingSenderId: '853950761426',
    projectId: 'note-with-firebase-33215',
    storageBucket: 'note-with-firebase-33215.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE-8K7C7CL4_DOUOtQlkxP05WvV2Ntnhw',
    appId: '1:853950761426:ios:e695e189f5bdec03abe00b',
    messagingSenderId: '853950761426',
    projectId: 'note-with-firebase-33215',
    storageBucket: 'note-with-firebase-33215.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE-8K7C7CL4_DOUOtQlkxP05WvV2Ntnhw',
    appId: '1:853950761426:ios:4cbb35a96cd5f956abe00b',
    messagingSenderId: '853950761426',
    projectId: 'note-with-firebase-33215',
    storageBucket: 'note-with-firebase-33215.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
